Combine CPG packages into one group for simultaneous updates
Fraunhofer-AISEC/codyze pull request #412
Opened 2022-02-02 13:37 UTC by fwendland

The CPG comes in multiple packages. To prevent renovate from creating a PR for each package, this configuration change groups them together.

This should prevent build errors where non-matching package versions are used.

2022-02-02 13:40 UTC, oxisto approved these changes

2022-02-02 13:43 UTC, oxisto requested changes

2022-02-02 13:43 UTC, oxisto commented on renovate.json
> +      "groupName": "CPG packages"
This is missing a }, here

2022-02-04 07:56 UTC, fwendland commented on renovate.json
> +      "groupName": "CPG packages"
Hmm ... forgot that one. Fixed.

2022-02-04 09:28 UTC, oxisto approved these changes

2022-02-04 09:28 UTC, merged